/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedClientPerfilRouteImport } from './routes/_authenticated/client/perfil'
import { Route as AuthenticatedProfessionalIndexRouteImport } from './routes/_authenticated/professional/index'
import { Route as AuthenticatedProfessionalPerfilRouteImport } from './routes/_authenticated/professional/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPerfilRoute =
  AuthenticatedClientPerfilRouteImport.update({
    id: '/client/perfil',
    path: '/client/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalIndexRoute =
  AuthenticatedProfessionalIndexRouteImport.update({
    id: '/professional/',
    path: '/professional/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalPerfilRoute =
  AuthenticatedProfessionalPerfilRouteImport.update({
    id: '/professional/perfil',
    path: '/professional/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/client/perfil': typeof AuthenticatedClientPerfilRoute
  '/professional/perfil': typeof AuthenticatedProfessionalPerfilRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/professional/': typeof AuthenticatedProfessionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/client/perfil': typeof AuthenticatedClientPerfilRoute
  '/professional/perfil': typeof AuthenticatedProfessionalPerfilRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/professional': typeof AuthenticatedProfessionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/client/perfil': typeof AuthenticatedClientPerfilRoute
  '/_authenticated/professional/perfil': typeof AuthenticatedProfessionalPerfilRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/professional/': typeof AuthenticatedProfessionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/client/perfil'
    | '/professional/perfil'
    | '/client/'
    | '/professional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/client/perfil'
    | '/professional/perfil'
    | '/client'
    | '/professional'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/onboarding'
    | '/_authenticated/client/perfil'
    | '/_authenticated/professional/perfil'
    | '/_authenticated/client/'
    | '/_authenticated/professional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/perfil': {
      id: '/_authenticated/client/perfil'
      path: '/client/perfil'
      fullPath: '/client/perfil'
      preLoaderRoute: typeof AuthenticatedClientPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/': {
      id: '/_authenticated/professional/'
      path: '/professional'
      fullPath: '/professional/'
      preLoaderRoute: typeof AuthenticatedProfessionalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/perfil': {
      id: '/_authenticated/professional/perfil'
      path: '/professional/perfil'
      fullPath: '/professional/perfil'
      preLoaderRoute: typeof AuthenticatedProfessionalPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedClientPerfilRoute: typeof AuthenticatedClientPerfilRoute
  AuthenticatedProfessionalPerfilRoute: typeof AuthenticatedProfessionalPerfilRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedProfessionalIndexRoute: typeof AuthenticatedProfessionalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedClientPerfilRoute: AuthenticatedClientPerfilRoute,
  AuthenticatedProfessionalPerfilRoute: AuthenticatedProfessionalPerfilRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedProfessionalIndexRoute: AuthenticatedProfessionalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
